---
title: "Use of custom Colors in ggplot2"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Use of custom Colors in ggplot2}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 7
)
```

```{r setup}
library(customColors)
library(shades)
library(ggplot2)
```

[Source](https://drsimonj.svbtle.com/creating-corporate-colour-palettes-for-ggplot2 "https://drsimonj.svbtle.com/creating-corporate-colour-palettes-for-ggplot2")

# Potline Colors

```{r showPotineColors}
# Base potline colors from jpeg picture
swatch(colorVectorPotline)
names(colorVectorPotline)
```

```{r extractColors}
swatch(extractColors("red", "greyRed", colorVector = colorVectorPotline))
```

```{r customPalettes}
# Palettes (set of colors) from color vector
potlinePalettes
purrr::map(potlinePalettes, swatch)
```

```{r interpolatePalette}
# Interpolate Palette to get more colors. Defaut palette is 'redBeigeGrey' from potlinePalette
swatch(interpolatePalette(paletteName = "grey", reverse = T)(10))
swatch(interpolatePalette()(4))
```

```{r usePotlineColors}
ggplot(iris, aes(Sepal.Width, Sepal.Length, color = Species)) +
    geom_point(size = 4) +
    scale_color_potline()
```

```{r usePotlineColors2}
ggplot(iris, aes(x = Sepal.Width, y = Sepal.Length, color = Sepal.Length)) +
  geom_point(size = 4 ) +
  scale_color_potline(discrete = F, palette = "pinkPurple", reverse = T)
  
```

```{r scaleFillPotline}
ggplot(mpg, aes(manufacturer, fill = manufacturer)) +
    geom_bar() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    scale_fill_potline(guide = "none") 

```

# Trimet Colors

```{r showTrimetColors}
swatch(colorVectorTrimet)
names(colorVectorTrimet)
trimetPalette
purrr::map(trimetPalette, swatch)
swatch(interpolatePalette(paletteName = "main",
                          paletteList = trimetPalette,
                          reverse = T)(10))
```

```{r useTrimetcolors}
ggplot(iris, aes(x = Sepal.Width, y = Sepal.Length, color = Sepal.Length)) +
  geom_point(size = 4 ) +
  scale_color_trimet(discrete = F, reverse = T) +
  theme(panel.background = element_rect(fill = "grey80"))
  
```

```{r scaleFillTrimet}
ggplot(mpg, aes(manufacturer, fill = manufacturer)) +
    geom_bar(color = "black") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    scale_fill_trimet(guide = "none") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90)) 

```
